### ISSUE TITLE
Add good readme

### ISSUE THREAD

**Issue by ludusrusso** [ludusrusso/pp-robot-2018#1]
Add a good description of the project in the readme!

**Comment by stefanocirici** [comment]
An initial version of [README.md](https://github.com/ludusrusso/pp-robot-2018/blob/documentation/README.md) has been added to the branch documentation. A pull request will be asked when further information will be added to the file.

**Comment by ludusrusso** [comment]
Nice!
please start write down the high level architecture of your project! 
And find a good name!!

**Comment by stefanocirici** [comment]
Documentation added and merged into master branch.
