### ISSUE TITLE
run ros on raspi

### ISSUE THREAD

**Issue by ludusrusso** [ludusrusso/pp-robot-2018#2]
```
# curl -sSL get.docker.io | bash
# docker pull hbrobotics/ros-base:rpi3
```

**Comment by lucaledda** [comment]
Ciao Ludovico,
ho completato il pull dell'immagine. Poi provo a lanciare "docker run ..." e mi risponde con il seguente errore:
"standard_init_linux.go:178: exec user process caused "exec format error"

Sto usando Ubuntu 16.04 LTS su macchina virtuale. Può essere quel problema di cui ci parlavi oggi?

**Comment by ludusrusso** [comment]
Hey!!

1. Official lang here is eng, please use it!
2. Thanks, add an issue on the [official repo on the project](https://github.com/HotBlackRobotics/docker-ros-base).. I'll try to fix it as soon as the issue is on!
